# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/work/tju/DE/Final/ball/project_1/project_1.srcs/sources_1/ip/music_lose/music_lose.xci
# IP: The module: 'music_lose' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/tju/DE/Final/ball/project_1/project_1.srcs/sources_1/ip/music_lose/music_lose_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'music_lose'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/work/tju/DE/Final/ball/project_1/project_1.srcs/sources_1/ip/music_lose/music_lose.xci
# IP: The module: 'music_lose' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/work/tju/DE/Final/ball/project_1/project_1.srcs/sources_1/ip/music_lose/music_lose_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'music_lose'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
